/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package pconfigdebugging

import pconfigdebugging.configuration.UtilsConfig
import pconfigdebugging.other.bar.ExtremelyComplexConfig
import pureconfig.ConfigSource
import pureconfig.generic.auto._

object Foo extends App {
  println("foo")
  // Simple class, works fine (fails at runtime as no properties are provided)
  // println(ConfigSource.default.load[ConfigFoo].right.get)

  // complex case
   //println(ConfigSource.default.load[ConfigComplex].right.get)
   println(UtilsConfig.loadConfiguration[ExtremelyComplexConfig])
}
